In [1]:
# WORKING WITH GRAPHS : WE HAVE A MODULE NAMED AS scipy.sparse.csgraph
# ADJACENCY MATRIX : nxn MATRIX WHERE n IS THE NUMBER OF ELEMENTS IN THE GRAPH.

import numpy as np
from scipy.sparse.csgraph import connected_components
from scipy.sparse import csr_matrix

a = np.array ([ [0,1,2] , [1,0,0] , [2,0,0] ])
b = csr_matrix(a)
print ( connected_components(b) )

(1, array([0, 0, 0]))


In [2]:
# dijkstra METHOD : FOR FINDING THE SHORTEST PATH IN A GRAPH FROM ONE ELEMENT TO ANOTHER ELEMENT.
# IT TAKES 3 ARGUMENTS : return_predecessors , indices , limit
# return_predecessors TAKES ONLY BOOLEAN VALUE.

import numpy as np
from scipy.sparse.csgraph import dijkstra
from scipy.sparse import csr_matrix

a = np.array ([ [0,1,2] , [1,0,0] , [2,0,0] ])
c = csr_matrix(a)
print ( dijkstra ( c , return_predecessors=True , indices=0 ) )

(array([0., 1., 2.]), array([-9999,     0,     0]))


In [3]:
# floyd_warshall METHOD : IT IS FOR FINDING SHORTEST PATH BETWEEN ALL THE PAIRS OF ELEMENTS.

import numpy as np
from scipy.sparse.csgraph import floyd_warshall
from scipy.sparse import csr_matrix

a = np.array ([ [0,1,2] , [1,0,0] , [2,0,0] ])
d = csr_matrix(a)
print ( floyd_warshall ( d , return_predecessors=True ) )

(array([[0., 1., 2.],
       [1., 0., 3.],
       [2., 3., 0.]]), array([[-9999,     0,     0],
       [    1, -9999,     0],
       [    2,     0, -9999]]))


In [4]:
''' bellman_ford METHOD : IT IS FOR FINDING SHORTEST PATH BETWEEN ALL THE PAIRS OF ELEMENTS 
BUT THIS METHOD CAN HANDLE NEGATIVE WEIGHT AS WEEL '''

import numpy as np
from scipy.sparse.csgraph import bellman_ford
from scipy.sparse import csr_matrix

e = np.array ([ [0,-1,2] , [1,0,0] , [2,0,0] ])
f = csr_matrix(e)
print ( bellman_ford ( f , return_predecessors=True , indices=0 ) )

(array([ 0., -1.,  2.]), array([-9999,     0,     0]))


In [5]:
# depth_first_order METHOD : IT RETURNS THE DEPTH FIRST TRAVERSAL FROM A NODE.
# IT TAKES 2 ARGUMENTS : THE GRAPH , STARTING POINT .

import numpy as np
from scipy.sparse.csgraph import depth_first_order
from scipy.sparse import csr_matrix

g = np.array ([ [0,1,0,1] , [1,1,1,1] , [2,1,1,0] , [0,1,0,1] ])
h = csr_matrix(g)
print ( depth_first_order (h,1) )

(array([1, 0, 3, 2]), array([    1, -9999,     1,     0]))


In [6]:
# breadth_first_order METHOD : IT RETURNS THE BREADTH FROM A NODE.
# IT TAKES 2 ARGUMENTS : THE GRAPH , STARTING POINT .

import numpy as np
from scipy.sparse.csgraph import breadth_first_order
from scipy.sparse import csr_matrix

g = np.array ([ [0,1,0,1] , [1,1,1,1] , [2,1,1,0] , [0,1,0,1] ])
i = csr_matrix(g)
print ( breadth_first_order (i,1) )

(array([1, 0, 2, 3]), array([    1, -9999,     1,     1]))
